export var Mascots = [
  "Aardvarks",
  "Abes",
  "Academics",
  "Aces",
  "Achaeans",
  "Acorns",
  "Agates",
  "Airedales",
  "Aklaqs",
  "Alacranes",
  "Alices",
  "Ambassadors",
  "Amcats",
  "Anchormen",
  "Andies",
  "Angoras",
  "Anteaters",
  "Antlers",
  "Appleknockers",
  "Applemen",
  "Apollos",
  "Arabs",
  "Archangels",
  "Archers",
  "Arcs",
  "Argylls",
  "Armadillos",
  "Armens",
  "Artesians",
  "Artichokes",
  "Athenians",
  "Atomics",
  "Atom Smashers",
  "Atoms",
  "Auctioneers",
  "Auggies",
  "Auks",
  "Avenging Angels",
  "Awesome Blossoms",
  "Baby Rattlers",
  "Badgers",
  "Bald Eagles",
  "Bambies",
  "Banana Slugs",
  "Bantams",
  "Barbs",
  "Barristers",
  "Battlers",
  "Battlin' Bears",
  "Battling Bathers",
  "Battling Bishops",
  "Bays",
  "Beacons",
  "Bearkats",
  "Beetdiggers",
  "Behrend Lions",
  "Belles",
  "Bellringers",
  "Bernardians",
  "Berries",
  "Big Blacks",
  "Big Green",
  "Big Green Machine",
  "Big Macs",
  "Big Red",
  "Big Trains",
  "Billies",
  "Billikens",
  "Billygoats",
  "Blackbirds",
  "Black Diamonds",
  "Black Flies",
  "Blackjacks",
  "Black Knights",
  "Blackshirts",
  "Blacksmiths",
  "Black Tornado",
  "Blazing Trojans",
  "Blizzards",
  "Blockbusters",
  "Bloodhounds",
  "Blue",
  "Blue and Blue",
  "Blue Blazes",
  "Blue Blazers",
  "Blue Bombardiers",
  "Blueboys",
  "Bluecats",
  "Blue Darters",
  "Blue Eagles",
  "Blue Hose",
  "Blue Ponies",
  "Blue Streaks",
  "Blugolds",
  "Bobkatz",
  "Bobwhites",
  "Boilermakers",
  "Boll Weevils",
  "Bombers",
  "Bonackers",
  "Bonnies",
  "Bookers",
  "Boomers",
  "Borderites",
  "Bowmen",
  "Boxers",
  "Brahmans",
  "Brewers",
  "Briar Jumpers",
  "Brickies",
  "Bridgers",
  "Britons",
  "Broncbusters",
  "Bruisers",
  "Bubblers",
  "Buckaroos",
  "Buckeyes",
  "Buckhorns",
  "Buckskins",
  "Buffanblu",
  "Builders",
  "Bulldawgs",
  "Bulldoggers",
  "Bullfrogs",
  "Bullpups",
  "Burghers",
  "Burkies",
  "Burros",
  "Burrs",
  "Bunnies",
  "Bushmen",
  "Buttons",
  "Caballeros",
  "Cahillites",
  "Caimans",
  "Caissons",
  "Camels",
  "Campers",
  "Canalmen",
  "Canefire",
  "Canaries",
  "Canners",
  "Cannoneers",
  "Canucks",
  "Caravan",
  "Cardinal",
  "Caseys",
  "Castle Guards",
  "Catamounts",
  "Cavers",
  "Caxys",
  "Cee Bees",
  "Centaurs",
  "Centurions",
  "Ceramics",
  "Challengers",
  "Chameleons",
  "Champions",
  "Chancellors",
  "Chanticleers",
  "Chaparrals",
  "Charging Wildcats",
  "Cheesemakers",
  "Chemics",
  "Chesty Lions",
  "Chipmunks",
  "Chimeras",
  "Chinooks",
  "Chitwhins",
  "Chix",
  "Chokers",
  "Chucks",
  "Chukars",
  "Churchmen",
  "Claim Jumpers",
  "Clerks",
  "Clockers",
  "Coalers",
  "Coasters",
  "Cobbers",
  "Cobblers",
  "Cogs",
  "Colonials",
  "Colonists",
  "Columbians",
  "Commodores",
  "Conchs",
  "Conquistadors",
  "Continentals",
  "Copperheads",
  "Copper Kings",
  "Cornhuskers",
  "Cornjerkers",
  "Corsairs",
  "Cossacks",
  "Cottonpickers",
  "Couriers",
  "Coursers",
  "Crabbers",
  "Cranes",
  "Crescents",
  "Crickets",
  "Criminals",
  "Crimson",
  "Crimson Tide",
  "Cristeros",
  "Cruisers",
  "Crushers",
  "Cubans",
  "Curley Wolves",
  "Cutters",
  "Cutthroats",
  "Daggers",
  "Daisies",
  "Danes",
  "Daredevils",
  "Darts",
  "Dashers",
  "Dateliners",
  "Delta Kings",
  "Democrats",
  "Demon Deacons",
  "Desert Shields",
  "Devilpups",
  "Diamond Hornets",
  "Dine Warriors",
  "Dinos",
  "Diplomats",
  "Disciples",
  "Discoverers",
  "Divers",
  "Dogies",
  "Donkeys",
  "Dons",
  "Dots",
  "Doughboys",
  "Doves",
  "Dragons",
  "Drakes",
  "Dreadnaughts",
  "Drifters",
  "Drovers",
  "Duhawks",
  "Dutch",
  "Dux",
  "Dynamiters",
  "Dynamos",
  "Eaglets",
  "Earwigs",
  "Eddies",
  "Eels",
  "Electrics",
  "Electrons",
  "Elis",
  "Elkers",
  "Elks",
  "Emeralds",
  "Emperors",
  "Ephs",
  "E-Rabs",
  "Eskymos",
  "Eutectic",
  "Evergreens",
  "Executives",
  "Explorers",
  "Exporters",
  "Feet",
  "Fightin' Blue Hens",
  "Fighting Clan",
  "Fighting Cocks",
  "Fighting Farmers",
  "Fighting 59ers",
  "Fighting Irish",
  "Fighting Leathernecks",
  "Fighting Leemen",
  "Fighting Muckers",
  "Fighting Muskies",
  "Fighting Okra",
  "Fighting Pickles",
  "Fighting Porcupines",
  "Fighting Sea Lions",
  "Fire Ants",
  "Firebrands",
  "Firestorm",
  "Fishermen",
  "Flaming Hearts",
  "Flivvers",
  "Flying Dutchmen",
  "Flying Fleet",
  "Flying Flucos",
  "Flying Forts",
  "Flying G's",
  "Flying Geese",
  "Flying Horses",
  "Flying L's",
  "Flying Squadron",
  "Fordians",
  "Fords",
  "Foresters",
  "14ers",
  "Freddies",
  "Friars",
  "Furies",
  "Fusion",
  "Galloping Ghosts",
  "Gamecocks",
  "Garnet",
  "Gauchos",
  "Gauls",
  "Geckos",
  "Generals",
  "Gentlemen",
  "Geoducks",
  "Gila Monsters",
  "G-Men",
  "Gnomes",
  "Go-Devils",
  "Go-Hawks",
  "Goldbugs",
  "Golden Bears",
  "Golden Flashes",
  "Golden Gales",
  "Golden Gators",
  "Golden Goblins",
  "Golden Gophers",
  "Golden Griffins",
  "Golden Gusties",
  "Golden Horde",
  "Golden Hurricane",
  "Golden Sandstorm",
  "Golden Tors",
  "Gold Rush",
  "Gondoliers",
  "Gore Rangers",
  "Gorillas",
  "Gorloks",
  "Goslings",
  "Governors",
  "Grangers",
  "Granite Diggers",
  "Grape Pickers",
  "Gray Bees",
  "Great Danes",
  "Great Lakers",
  "Greenbacks",
  "Green Bears",
  "Green Mountain Boys",
  "Green Terror",
  "Green Wave",
  "Gremlins",
  "Grenadiers",
  "Grey Ghosts",
  "Greyhounds",
  "Grizzly Cubs",
  "Grovers",
  "Guardians",
  "Gumbies",
  "Gyrenes",
  "Halfbreeds",
  "Hambletonians",
  "Hardrockers",
  "Harlem Hellfighters",
  "Harpooners",
  "Harriers",
  "Hatchets",
  "Hatters",
  "Hawkeyes",
  "Hawklets",
  "Haybalers",
  "Haymakers",
  "Headless Horsemen",
  "Helmsmen",
  "Hematites",
  "Hermits",
  "Highclimbers",
  "Highland Cavaliers",
  "Highwaymen",
  "Hilanders",
  "Hi-Liners",
  "Hillbillies",
  "Hillcats",
  "Hillclimbers",
  "Hillers",
  "Hilltoppers",
  "Hippos",
  "Hoboes",
  "Hodags",
  "Hoggers",
  "Hokies",
  "Honey Badgers",
  "Honey Bears",
  "Honkers",
  "Hoosiers",
  "Horned Frogs",
  "Horned Toads",
  "Horsemen",
  "Hot Dogs",
  "Houn' Dawgs",
  "Howlers",
  "Hoyas",
  "Hubbers",
  "Hubs",
  "Huntsmen",
  "Hustler Bees",
  "Hustlin' Owls",
  "Hustling Quakers",
  "Hyaks",
  "Ichabods",
  "Impalas",
  "Imperials",
  "Imps",
  "Inferno",
  "Ingots",
  "Inventors",
  "Ironheads",
  "Ironmen",
  "Iron Mikes",
  "Irrigators",
  "Jacks",
  "Jaegers",
  "Jaspers",
  "Javelinas",
  "Jayhawks",
  "Jeeps",
  "Jeffs",
  "Jegos",
  "Jems",
  "Jersey Blues",
  "Jesters",
  "Jesuits",
  "Jimmies",
  "Johnnies",
  "Judges",
  "Juggernauts",
  "Jugglers",
  "Jug Rox",
  "Jumbos",
  "Jungaleers",
  "Junior Billikens",
  "Junior Jays",
  "Junior Rainbows",
  "Junior Ravens",
  "Ka Makani",
  "Kangaroos",
  "Kares",
  "Kavemen",
  "Keelhaulers",
  "Kernels",
  "Kewpies",
  "Keydets",
  "Kicking Mules",
  "Killer Whales",
  "Kilties",
  "Kings",
  "Kingsmen",
  "Kittens",
  "Knotty Oakers",
  "Koalas",
  "Kodiaks",
  "Kohawks",
  "Kokanee",
  "Konkrete Kids",
  "Koyotes",
  "Lambkins",
  "Lancers",
  "Larks",
  "Larries",
  "Lasers",
  "Lawyers",
  "Lava Bears",
  "Ledgers",
  "Liberators",
  "Light",
  "Li'l Irish",
  "Links",
  "Lions of Judah",
  "Little Cyclones",
  "Little Dutchmen",
  "Little Giants",
  "Little Gophers",
  "Little Green",
  "Little Hawks",
  "Little Hoyas",
  "Little Johns",
  "Little Lions",
  "Little Muskies",
  "Little Prexies",
  "Little Red",
  "Llamas",
  "Lobos",
  "Loconets",
  "Longhorns",
  "Lopers",
  "Lords",
  "Lord Jeffs",
  "Lunas",
  "Lutes",
  "Lyncs",
  "Maccabees",
  "Magi",
  "Magicians",
  "Magic Storm",
  "Maiingan",
  "Main Streeters",
  "Majors",
  "Makos",
  "Malemutes",
  "Manatees",
  "Maniacs",
  "Marists",
  "Marcos",
  "Markers",
  "Marksmen",
  "Marshmen",
  "Martians",
  "Martlets",
  "Masai Lions",
  "Mastodons",
  "Matadors",
  "Mawrtians",
  "Mayhem",
  "Mean Green",
  "Mean Moose",
  "Mechanics",
  "Mercuries",
  "Meloneers",
  "Menehunes",
  "Midgets",
  "Midshipmen",
  "Mighty Bad Hawks",
  "Mighty Hoppers",
  "Mightymen",
  "Mighty Mikes",
  "Millionaires",
  "Minutemen",
  "Missionaries",
  "Moccasins",
  "Mocs",
  "Modeltowners",
  "Moguls",
  "Monarchs",
  "Mongoose",
  "Monks",
  "Monsoons",
  "Moors",
  "Morning Stars",
  "Moundbuilders",
  "Movin' Maroons",
  "Muhls",
  "Muleriders",
  "Mules",
  "Muleskinners",
  "Musher Dogs",
  "Musketeers",
  "Muskrats",
  "Mystics",
  "Na Alii",
  "Nads",
  "Nanooks",
  "Naps",
  "Navigators",
  "Nikes",
  "Nimrods",
  "Nittany Lions",
  "Noises",
  "Nor'easters",
  "Normans",
  "Norse",
  "Northern Lights",
  "Nubians",
  "Oatkan Knights",
  "Obezags",
  "Ocelots",
  "Ogichida",
  "Old Abes",
  "Oles",
  "Orabs",
  "Oracles",
  "Orange",
  "Orcas",
  "Orediggers",
  "Oredockers",
  "Orphans",
  "Ospreys",
  "Otters",
  "Outlaws",
  "Oxen",
  "Oysters",
  "Paladins",
  "Palominos",
  "Pam Pack",
  "Pandas",
  "Papermakers",
  "Parrots",
  "Parsons",
  "Pathfinders",
  "Peacocks",
  "Peglegs",
  "Pendragons",
  "Penguins",
  "Penmen",
  "Peregrines",
  "Piasa Birds",
  "Pied Pipers",
  "Pine Lads",
  "Piners",
  "Pintos",
  "Piranhas",
  "Planets",
  "Plowboys",
  "Poets",
  "Pointers",
  "Polar Bears",
  "Polars",
  "Pomeroys",
  "Ponies",
  "Popes",
  "Portagers",
  "Porters",
  "Potters",
  "Prairie Fire",
  "Praying Colonels",
  "Preachers",
  "Preppers",
  "Presidents",
  "Pretzels",
  "Privateers",
  "Professors",
  "Pronghorns",
  "Prophets",
  "Provets",
  "Prowlers",
  "Pterodactyls",
  "Pueo",
  "Pugs",
  "Punchers",
  "Purgolders",
  "Purples",
  "Purple Pounders",
  "Purple Tornadoes",
  "Pythians",
  "Qaavik",
  "Quarriers",
  "Quasars",
  "Queensmen",
  "Quips",
  "Racers",
  "Ragin' Cajuns",
  "Railroaders",
  "Rainbow Warriors",
  "Rajahs",
  "Ramblers",
  "Ramblin' Wreck",
  "Rampants",
  "Rappites",
  "Razorbacks",
  "Reapers",
  "Rebel Bulls",
  "Red Ants",
  "Redbugs",
  "Redcoats",
  "Reddies",
  "Red Elephants",
  "Red Foxes",
  "Red Heifers",
  "Red Ravens",
  "Red Riots",
  "Red Rocketeers",
  "Red Rovers",
  "Redsides",
  "Redstickers",
  "Red Terrors",
  "Red Tops",
  "Refiners",
  "Regents",
  "Reggies",
  "Reivers",
  "Resorters",
  "Retrievers",
  "Revelators",
  "Ricebirds",
  "Riders",
  "Ridgerunners",
  "Ringnecks",
  "Rivals",
  "Riverbats",
  "River Kings",
  "River Rats",
  "Roadrunners",
  "Roaring Lions",
  "Rock-a-Chaws",
  "Rockcrushers",
  "Rocks",
  "Ro-Hawks",
  "Romans",
  "Roneagles",
  "Roosters",
  "Ropers",
  "Roses",
  "Roughers",
  "Roughnecks",
  "Royal Comets",
  "Running Eagles",
  "Russets",
  "Saddleites",
  "Sagehens",
  "Sages",
  "Sailfish",
  "Sallies",
  "SaltHawks",
  "Salukis",
  "Sammies",
  "Samsons",
  "Samurai",
  "Sandcrabs",
  "Sandites",
  "Sand Lizards",
  "Sand Sharks",
  "Sandstoners",
  "Sartans",
  "Sasquatch",
  "Satellites",
  "Savage Heat",
  "Savage Storm",
  "Sawyers",
  "Scarabs",
  "Scarlet Fliers",
  "Scoopers",
  "Scrappers",
  "Screaming Devils",
  "Screaming Penguins",
  "Sea Aggies",
  "Sea Beggars",
  "Seagulls",
  "Seahorses",
  "SeaKings",
  "Seal Pups",
  "Sea Parrots",
  "Seasiders",
  "Seaters",
  "Senators",
  "Seraphs",
  "Serpents",
  "Setters",
  "Sheepherders",
  "Sheiks",
  "Shells",
  "Sherman Tanks",
  "Shiners",
  "Ships",
  "Shipbuilders",
  "Shires",
  "Shiretowners",
  "Shockers",
  "Shoremen",
  "Shorians",
  "Shorthorns",
  "Sidewinders",
  "Silver Foxes",
  "Silverswords",
  "Sir Bills",
  "Sissaungi",
  "613s",
  "Skeeters",
  "Skiers",
  "Skipjacks",
  "Skirts",
  "Skylanders",
  "Skyrockets",
  "Slaters",
  "Slicers",
  "Smithies",
  "Smoky Bears",
  "Snails",
  "Solons",
  "Sooners",
  "Space Pioneers",
  "Sparkplugs",
  "Speedboys",
  "Spiders",
  "Spires",
  "Spoilers",
  "Spongers",
  "Spoofhounds",
  "Springers",
  "Spuds",
  "Spudders",
  "Spy Ponders",
  "Soaring Eagles",
  "Sobos",
  "SonBlazers",
  "Squirrels",
  "Stags",
  "Stanners",
  "Stateliners",
  "Steamers",
  "Steamrollers",
  "Steelmen",
  "Stingarees",
  "Stockaders",
  "Stormin' Pointers",
  "Stormy Petrels",
  "Strivers",
  "Strutting Jaguars",
  "Student Princes",
  "Sugar Beeters",
  "Sultans",
  "Sunbirds",
  "Super Larks",
  "Swamp Foxes",
  "Swathers",
  "Swedes",
  "Swifts",
  "Sycamores",
  "Syrupmakers",
  "Talbots",
  "Tanagers",
  "Tanners",
  "Tarantulas",
  "Tarbabes",
  "Tarblooders",
  "Tar Heels",
  "Tarriers",
  "Tars",
  "Tartans",
  "Tartars",
  "Techmen",
  "Technicians",
  "Teddies",
  "Tejanos",
  "Templars",
  "Terrapins",
  "Terriers",
  "Teutons",
  "The Rock",
  "Thorobreds",
  "Thorpes",
  "Threshers",
  "Thunderbirds",
  "Thunder Chicken",
  "Thunderducks",
  "Thundering Herd",
  "ThunderWolves",
  "Tides",
  "Tigercats",
  "Tiger Cubs",
  "Tigerhawks",
  "Tigersharks",
  "TigerScots",
  "Tillers",
  "Titans",
  "T-Jacks",
  "Toilers",
  "Tologs",
  "Tomcats",
  "Tommies",
  "Torchbearers",
  "Torches",
  "Toreros",
  "Torreys",
  "Townies",
  "Tracers",
  "Tractors",
  "Trainers",
  "Trappers",
  "Trevians",
  "Tribunes",
  "Tritons",
  "Trollers",
  "Trolls",
  "Troubadors",
  "Truckers",
  "Turkeys",
  "Turks",
  "Tuskers",
  "Unicorns",
  "Urchins",
  "Valkyries",
  "Valley Cubs",
  "Vandals",
  "Vaqueros",
  "Vee Bees",
  "Vendeens",
  "Ventures",
  "V-Hawks",
  "Victors",
  "Villagers",
  "Villains",
  "Villa Novans",
  "Vineyarders",
  "Violets",
  "Vivettes",
  "Vixens",
  "Voks",
  "Volunteers",
  "Voyageurs",
  "Vulcans",
  "Wahawks",
  "Wahoos",
  "Wardens",
  "Wardogs",
  "Warlords",
  "Wambdi",
  "Wampus Cats",
  "Wapiti",
  "Warhorses",
  "Wasps",
  "Watchdogs",
  "Watchmen",
  "Waves",
  "Webbies",
  "Westcos",
  "Westies",
  "Wheelers",
  "Whippets",
  "Whip-Purs",
  "Whirlies",
  "White Buffaloes",
  "Whitefaces",
  "White Mules",
  "Wild Boars",
  "Wildebeests",
  "Wild Gators",
  "Wildkits",
  "Windjammers",
  "Winged Beavers",
  "Winged Lions",
  "Witches",
  "Wombats",
  "Wonderboys",
  "Wonders",
  "Woodchucks",
  "Wood Ducks",
  "Wooden Shoes",
  "Woolies",
  "Wreckers",
  "Wrecking Crew",
  "Wrens",
  "Wykons",
  "Wyverns",
  "Yachtsmen",
  "Yaks",
  "Yeguas",
  "Yellowhammers",
  "Yeomen",
  "Yoemen",
  "Zags",
  "Zebras",
  "Zee Bees",
  "Zephyrs",
  "Zeps",
  "Zips",
  "Zizzers"
  ];